### ISSUE TITLE
Unwrap spawnSyncBinding.spawn?

### ISSUE THREAD

**Issue by lijunle** [tapjs/spawn-wrap#39]
Hi, this line in `unwrap` function looks strange:

```js
if (spawnSyncBinding) {
  spawnSync = spawnSyncBinding.spawn // <----- this line
}
```

> https://github.com/tapjs/spawn-wrap/blob/master/index.js#L60

I think you want to write `spawnSyncBinding.spawn = spawnSync`.

**Comment by isaacs** [comment]
Fixed on master.
