### ISSUE TITLE
Not-node/iojs cmdname should also happen on Windows.

### ISSUE THREAD

**Issue by lijunle** [tapjs/spawn-wrap#40]
Hi,

I saw there is [a special logic](https://github.com/tapjs/spawn-wrap/blob/master/index.js#L313-L316) to handle cmdname which is not `node` or `iojs`. Such logic should also happen in [Window if-branch](https://github.com/tapjs/spawn-wrap/blob/master/index.js#L297).

/cc @evanlucas

**Comment by isaacs** [comment]
Should be updated on master.  try `npm i spawn-wrap@next` to pull the 1.3 version.
