### ISSUE TITLE
Can a new patch be published?

### ISSUE THREAD

**Issue by MylesBorins** [tapjs/spawn-wrap#53]
[A patch](https://github.com/tapjs/spawn-wrap/commit/18009ac8994ed4c56159b012add4e0d7819581a9) recently landed that fixes that test suite. Until a new release has been made this module is failing in CITGM.

For the time being I'm going to set spawn-wrap to skip so it is not affecting the results of the CI. Please close this issue when a new release has been made and we'll revert the skip

**Comment by gibfahn** [comment]
[v1.3.6](https://github.com/tapjs/spawn-wrap/tree/v1.3.6) fixes the issue. This can be closed.
