### ISSUE TITLE
shelljs does not seem to work wrapped child process

### ISSUE THREAD

**Issue by philkunz** [tapjs/spawn-wrap#59]
For some reason shelljs does not seem to work with spawn wrap... Does anyone else have the same problem?

**Comment by pkunzexternal** [comment]
The reason for this is spawn-wrap setting process.env.PATH with some internal id that I don't get why it is there.

**Comment by philkunz** [comment]
So just make sure you populate process.env.PATH from the parent to the wrapped child process :)
