### ISSUE TITLE
bug: spawn-wrap@1.4.0 creates `undefined` folder

### ISSUE THREAD

**Issue by bcoe** [tapjs/spawn-wrap#64]
I've been doing some testing with `spawn-wrap@1.4.0` with nyc. I'm noticing that an `undefined` folder is created whenever spawn-wrap is executed. I'm guessing this is related to the `mkdirp` logic that was introduced to create working directories.

CC: @chadxz, @gautaz

**Comment by chadxz** [comment]
I can reproduce that issue

**Comment by chadxz** [comment]
it's because https://github.com/tapjs/spawn-wrap/blob/master/index.js#L15 should say `home + ` instead of `homedir +`. Will post a PR

**Comment by czy88840616** [comment]
have some publish plan for this patch ?

**Comment by guangwong** [comment]
+1

**Comment by welladamm** [comment]
@bcoe can we publish a `1.4.1` release to include this fix, please?

**Comment by bcoe** [comment]
@isaacs mind publishing a patch release when you have a moment; this will stop a bug that's creating the scripts directory in the wrong location.

**Comment by isaacs** [comment]
fixed on 1.4.1
